ci(push-or-pull): add qjs build for cli.test.ts

diff --git a/.github/workflows/on-push-or-pull.yml b/.github/workflows/on-push-or-pull.yml
--- a/.github/workflows/on-push-or-pull.yml
+++ b/.github/workflows/on-push-or-pull.yml
@@ -15,8 +15,98 @@ on:
       - master
 
 jobs:
+
+  #----------------------------------------------------------------------------#
+  #@id::build cli for executable builds                                        #
+  #----------------------------------------------------------------------------#
+  setup:
+    runs-on: ubuntu-latest
+    steps:
+      - name: checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: bun::preheat-cache
+        if: env.USE_CACHE == 1
+        uses: actions/cache@v4
+        with:
+          path: ~/.bun/install/cache
+          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-bun-
+
+      - name: bun::preheat-oven
+        uses: oven-sh/setup-bun@v2
+        with:
+          bun-version: latest
+
+      # install deps & make all
+      - name: make::install
+        run: make install
+
+      - name: verify::node_modules
+        run: |
+          set -eu
+          test -d ./node_modules || (echo "node_modules not found!" && exit 1)
+
+      # make build
+      - name: make::build
+        run: make build
+
+      # make build_cli
+      - name: make::build_cli
+        run: make build_cli
+
+      # make build_cli_quickjs
+      - name: make::build_cli_quickjs
+        run: make build_cli_quickjs
+
+
+  #----------------------------------------------------------------------------#
+  #@id::linux executable                                                       #
+  #----------------------------------------------------------------------------#
+  linux:
+    needs: setup
+    runs-on: ubuntu-22.04
+    strategy:
+      fail-fast: false
+      matrix:
+        arch: [x86_64]
+    steps:
+      - name: checkout
+        uses: actions/checkout@v4
+        with:
+          repository: 'quickjs-ng/quickjs'
+          path: 'quickjs-ng'
+
+      - name: setup
+        uses: jirutka/setup-alpine@v1
+        with:
+          arch: ${{matrix.arch}}
+          packages: 'build-base make cmake'
+
+      - name: build::quickjs
+        shell: alpine.sh {0}
+        run: |
+          set -eu
+          cd quickjs-ng
+          mkdir build
+          cd build
+          cmake -DCMAKE_BUILD_TYPE=Release -DQJS_BUILD_CLI_STATIC=ON ..
+          cd ..
+          cmake --build build --target qjs_exe -j$(getconf _NPROCESSORS_ONLN)
+
+      - name: upload
+        uses: actions/upload-artifact@v4
+        with:
+          name: qjs
+          path: quickjs-ng/build/qjs
+
+
   build:
     runs-on: ubuntu-latest
+    needs: linux
     steps:
       - name: checkout
         uses: actions/checkout@v4
@@ -42,6 +132,31 @@ jobs:
       - name: make::install
         run :  make install
 
+      # download all built executables
+      - name: get::qjs:executable
+        uses: actions/download-artifact@v4
+        with:
+          path: build
+          merge-multiple: true
+
+      - name: list::build
+        run: ls -la build/
+
+      # set perms
+      - name: chmod::qjs
+        run: chmod +x build/qjs
+
       # the 'make release' target does it release: clean, setup, build, lint, test, aok (the entire jamboree)
+      # make release - need to specify local qjs to compile target in release
       - name: make::release
-        run :  make release
+        run: BIN_QJS=build/qjs DEBUG=1 make release
+
+      # rm qjs
+      - name: rm::build
+        run: rm -rf build
+
+      - name: verify::output
+        run: |
+          set -eu
+          ls -la dist/
+          test -f dist/index.js || (echo "dist/index.js not found!" && exit 1)
